from ed.secuenciales.ListaFIFO import Cola
from ed.secuenciales.ListaLIFO import Pila

"""Prueba del Cola y Pila"""


if __name__ == "__main__":
    cola = Cola()
    pila = Pila()
    
    # print("Cola")
    # print(cola.es_vacia())
    # print(cola)
    # cola.encolar(10)
    # cola.encolar(20)
    # cola.encolar(30)
    # print(cola.es_vacia())
    # print(cola.desencolar())
    # print(cola)
    # print(cola.desencolar())
    # print(cola)
    # print(cola.desencolar())
    # print(cola)
    # print(cola.desencolar())
    # print(cola)
    # print(cola.encolar("Hola"))
    # print(cola)
    # print(cola.encolar("Chao"))
    # print(cola)
    # print(cola.frente())
    # print(len(cola))
    # print(cola.desencolar())
    # print(cola)
    # print(cola.desencolar())
    # print(cola)
    # print(cola.desencolar())
    # print(cola)

    print("Pila")
    print(pila.es_vacia())
    print(pila)
    pila.apilar(10)
    pila.apilar(20)
    pila.apilar(30)
    print(pila.es_vacia())
    print(pila.desapilar())
    print(pila)
    print(pila.desapilar())
    print(pila)
    print(pila.desapilar())
    print(pila)
    print(pila.desapilar())
    print(pila)
    print(pila.apilar("Hola"))
    print(pila)
    print(pila.apilar(2))
    print(pila)
    print(pila.cima())
    print(len(pila))
    print(pila.desapilar())
    print(pila)
    print(pila.desapilar())
    print(pila)
    print(pila.desapilar())
    print(pila)
